version: 2

models:
  - name: stg_invoices
    description: Staging model for invoice data from Silver Screen theaters, containing billing information for movie showings at various locations
    columns:
      - name: movie_id
        description: Unique identifier for each movie, often composed of a combination of studio, year, and a unique code
          
      - name: invoice_date
        description: The month in which the invoice was issued, in the format YYYY-MM-DD
          
      - name: location_id
        description: The identifier of the movie theater location where the movie was shown
          
      - name: studio
        description: The production studio responsible for the movie, such as Pixar, Marvel Studios, etc.
        
      - name: invoice_id
        description: A unique identifier for each invoice issued for a specific movie at a specific location during a particular month
          
      - name: weekly_price
        description: The weekly price charged for showing the movie at the specific location

  - name: stg_movie_catalogue
    description: Staging model for movie catalogue data containing detailed information about movies released in 2024 and rented out by Silver Screen
    columns:
      - name: movie_id
        description: Unique identifier for each movie, often composed of a combination of studio, year, and a unique code
          
      - name: movie_title
        description: The title of the movie (defaulted to 'Unknown' if null)
          
      - name: genre
        description: The genre of the movie, describing the type of content (defaulted to 'Unknown' if null)
          
      - name: studio
        description: The production studio responsible for making the movie (defaulted to 'Unknown' if null)
          
      - name: budget
        description: The production budget of the movie, typically in dollars

  - name: stg_nj_001
    description: Staging model for transaction data from Silver Screen location NJ_001, containing individual ticket purchase transactions
    columns:
      - name: transaction_date
        description: The date when the transaction occurred, converted from timestamp to date format
          
      - name: movie_id
        description: Unique identifier for each movie, often composed of a combination of studio, year, and a unique code
          
      - name: ticket_amount
        description: The number of tickets purchased in this particular transaction (defaulted to 0 if null)
          
      - name: ticket_price
        description: The price per ticket for the transaction (defaulted to 0 if null)
          
      - name: location_id
        description: Static identifier for this theater location ('NJ_001')

  - name: stg_nj_002
    description: Staging model for daily sales data from Silver Screen location NJ_002, containing aggregated ticket sales information
    columns:
      - name: transaction_date
        description: The date of the ticket sales transaction, formatted as YYYY-MM-DD
          
      - name: movie_id
        description: Unique identifier for each movie, often composed of a combination of studio, year, and a unique code
          
      - name: ticket_amount
        description: The number of tickets sold on the given day (defaulted to 0 if null)
          
      - name: ticket_price
        description: The price per ticket sold on that particular day (defaulted to 0 if null)
          
      - name: location_id
        description: Static identifier for this theater location ('NJ_002')

  - name: stg_nj_003
    description: Staging model for ticket purchase data from Silver Screen location NJ_003, filtered to include only ticket transactions
    columns:
      - name: transaction_date
        description: The date when the transaction occurred, converted from timestamp to date format
          
      - name: movie_id
        description: Movie identifier extracted from the details field for ticket transactions
          
      - name: ticket_amount
        description: The quantity of tickets purchased in the transaction (defaulted to 0 if null)
          
      - name: ticket_price
        description: The price per ticket sold (defaulted to 0 if null)
          
      - name: location_id
        description: Static identifier for this theater location ('NJ_003')